{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "userapp.backend.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "userapp.backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }} 