{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "userapp.frontend.fullname" . }}-service
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "userapp.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "userapp.frontend.selectorLabels" . | nindent 4 }}
{{- end }} 