{{- if .Values.postgres.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "userapp.postgres.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "userapp.postgres.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.postgres.replicaCount }}
  selector:
    matchLabels:
      {{- include "userapp.postgres.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "userapp.postgres.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgres
          image: "{{ .Values.global.imageRegistry }}{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgres.service.port }}
              protocol: TCP
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: {{ include "userapp.postgres.fullname" . }}-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ include "userapp.postgres.fullname" . }}-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "userapp.postgres.fullname" . }}-secret
                  key: POSTGRES_PASSWORD
          {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          {{- end }}
          {{- if .Values.postgres.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.postgres.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.postgres.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.postgres.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ include "userapp.postgres.fullname" . }}-pvc
      {{- end }}
{{- end }} 