{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "userapp.postgres.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "userapp.postgres.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.postgres.secret }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end }} 