# Development values for userapp
# This file contains development-specific configurations

# Global settings
global:
  imageRegistry: ""
  imagePullSecrets: []

# Namespace configuration
namespace:
  create: true
  name: userapp-dev

# Ingress configuration
ingress:
  enabled: false  # Disable ingress for development

# Frontend configuration
frontend:
  enabled: true
  image:
    repository: userapp-frontend
    tag: latest
    pullPolicy: Never  # For local development
  replicaCount: 1
  service:
    type: NodePort  # Use NodePort for easy access
    port: 3000
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  config:
    REACT_APP_API_URL: http://localhost:5000

# Backend configuration
backend:
  enabled: true
  image:
    repository: userapp-backend
    tag: latest
    pullPolicy: Never  # For local development
  replicaCount: 1
  service:
    type: NodePort  # Use NodePort for easy access
    port: 5000
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  config:
    DB_HOST: postgres-service
    DB_NAME: userdb
    DB_PORT: "5432"
    PORT: "5000"
  uploads:
    storage:
      type: emptyDir
      size: 1Gi

# PostgreSQL configuration
postgres:
  enabled: true
  image:
    repository: postgres
    tag: 15-alpine
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5432
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  config:
    POSTGRES_DB: userdb
    POSTGRES_USER: postgres
  secret:
    POSTGRES_PASSWORD: "password"
  persistence:
    enabled: false  # Use emptyDir for development
    storageClass: ""
    size: 8Gi
    accessMode: ReadWriteOnce 